### ISSUE TITLE
How can I use Eagleye in MGRS coordinates

### ISSUE THREAD

**Issue by meliketanrikulu** [MapIV/eagleye#291]
I want to see my position in MGRS coordinates. I changed this launch file configuration --> https://github.com/MapIV/eagleye/blob/94228d3b646b82d24e7d5565f819c82ed4113abc/eagleye_util/fix2pose/launch/fix2pose.launch.xml#L12C1-L12C1 (I set tf_num = 2). But its not working . I tested with example rosbag .

Here is my output: 
![eagleye_MGRS](https://github.com/MapIV/eagleye/assets/41450930/62c92017-65a9-4765-8dda-e8de7c904041)
 You can see here '/eagleye/pose' topics output on terminal and RVIZ .

How can I get my position in MGRS coordinates.

**Comment by rsasaki0109** [comment]
Is eagleye/fix outputting the correct latitude and longitude?
I would like to see what the eagleye terminal output looks like.

**Comment by meliketanrikulu** [comment]
eagleye/fix output is looks correct. I convert UTM with local origin using eagleye/fix output (its blue line in the rviz screen) . It looks okey . But /eagleye/pose topic (its output of the fix2pose_node ) is not correct. And also here is the eagleye terminal output
![issue_eagleye](https://github.com/MapIV/eagleye/assets/41450930/5bcd6008-cf49-48ef-8cb1-f57de87578b4)

**Comment by rsasaki0109** [comment]
There was a problem and it has been corrected.
https://github.com/MapIV/eagleye/pull/295

The fix2pose node was dead in the following.
```
      std::cerr << "\033[31;1mError: Straddling over 3 grids is not supported.\033[m" << std::endl;
```
https://github.com/MapIV/llh_converter/blob/main/src/llh_converter.cpp#L453

**Comment by meliketanrikulu** [comment]
Now its not give result in this --> (eagleye/fix) topic. But still its still not working in MGRS coordinates.

**Comment by rsasaki0109** [comment]
Is the[ fix2pose node](https://github.com/MapIV/eagleye/tree/main-ros2/eagleye_util/fix2pose) dead? Could you check the fix2pose log file in the .ros directory to identify what the issue might be?
